---
version: "3"

services:
  desktainer-plus:
    image: dmotte/desktainer-plus
    build: docker-build
    restart: always
    hostname: desktainer-plus
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
      - "2222:22"   # SSH
      - "4200:4200" # Shellinabox
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # OpenSSH server host keys
      - ./ssh-host-keys/ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key:ro
      - ./ssh-host-keys/ssh_host_dsa_key.pub:/etc/ssh/ssh_host_dsa_key.pub:ro
      - ./ssh-host-keys/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - ./ssh-host-keys/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      - ./ssh-host-keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./ssh-host-keys/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      - ./ssh-host-keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./ssh-host-keys/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
    environment:
      RESOLUTION: 1440x900
      PASSWORD: debian
      VNC_PASSWORD: debian
