---
name: docker

# This workflow requires a DOCKERHUB_PASSWORD secret to be defined in the GitHub
# repository settings.

on:
  push:
    branches: [main]
    paths:
      - docker-build/**
      - .github/workflows/docker.yml
  schedule:
    # Runs automatically on the 27th of every month at 05.30 UTC
    - cron:  "30 05 27 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: docker-build
          platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64
          push: true
          tags: dmotte/desktainer-plus

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
