---
name: docker-description

# This workflow requires a DOCKERHUB_PASSWORD secret to be defined in the GitHub
# repository settings.

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/docker-description.yml

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dmotte/desktainer-plus
          short-description: Remote desktop in a container (extended version)
